apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /video-library(.*) $1 break;
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/video-library"
            backend:
              service:
                name: video-library-svc
                port:
                  number: 8080
