version: '3'
services:

  videolibrary-hub:
    image: sivaprasadreddy/videolibrary
    container_name: videolibrary-hub
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
