version: '3'
services:

  videolibrary:
    #image: sivaprasadreddy/videolibrary
    build: ../video-library
    container_name: videolibrary
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - vl-postgresdb
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://vl-postgresdb:5432/videolibrary
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APPLICATION_LOGSTASH_HOST: logstash
      LOGGING_FILE_NAME: /logs/videolibrary.log
      APPLICATION_DATAIMPORT_MAX_SIZE: 500
    volumes:
      - ../logs:/logs
  vl-postgresdb:
    image: postgres:12.3
    container_name: vl-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videolibrary
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres-data/videolibrary:/var/lib/postgresql/data